name: odin
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  duration: ^4.0.3
  dynamic_color: ^1.7.0
  emoji_picker_flutter: ^4.3.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_datetime_picker_plus: ^2.2.0
  flutter_hooks: ^0.20.5
  flutter_icons_catalog:
    git: https://github.com/ThisIsSidam/flutter_icons_catalog/
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  intl: ^0.19.0
  lottie: ^3.3.1
  objectbox: ^4.1.0
  objectbox_flutter_libs: ^4.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  quiver: ^3.2.2
  reactive_forms: ^17.0.1
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.2
  toastification: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  objectbox_generator: ^4.1.0
  riverpod_generator: 2.6.3
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
